### ISSUE TITLE
Item is not showing 100%

### ISSUE THREAD

**Issue by Wammy99** [tullamods/Bagnon#1447] opened 2022-10-24 03:43 UTC
**Running Software (issues missing this information will be deleted):**
 - Addon version: Bagnon-10.0.3-3.4.0
 - Server patch: [e.g. Build 8.0.1.27178] 10.0.3-3.4.0

 **Have you read the changelog? (please don't waste our time)**
 Mark if read. yes

**Describe the bug**
A clear and concise description of what the bug is. --After open bag. Part of items not showing background see picture! If i move bags litle it is fine again until next time i open bagnon.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'Open bag...'
2. Click on 'show item....'

**Expected behaviour**
A clear and concise description of what you expected to happen. See picture 02

**Screenshots**

**Error Logs**
Type `/console scriptErrors 1` in the chat and reload the game. If an error window appears, write here the message with `ID: 1` (labelled 1/X). This is generally NOT the message that the window shows by default.

**Additional context**
![Bagnon01-2022-10-24](https://user-images.githubusercontent.com/116535657/197444447-045fb25b-63c4-41bf-b614-7765d87f9378.jpg)
![Bagnon02-2022-10-24](https://user-images.githubusercontent.com/116535657/197444449-ddce82a1-0b67-4b09-8f19-3cba97265ca9.jpg)
![Bagnon01-2022-10-24](https://user-images.githubusercontent.com/116535657/197444483-88530766-a358-4e2c-a391-69fbd9be0b74.jpg)
![Bagnon02-2022-10-24](https://user-images.githubusercontent.com/116535657/197444491-3b099ed0-035f-4119-a08e-c015ca29aa9a.jpg)

**Comment by Wammy99** [comment] 2022-10-24 03:45
This hapend after last patch/uppdate of the Addon

**Comment by 7h3Cub3** [comment] 2022-10-24 11:47
Hello,

Same issue here (tooltip background not loading), from what i can see the issue doesn't happen with the default blizzard tooltip, i use an addon for tooltips called TipTac and it happens with it.

Hope that help.

cheers.

**Comment by JosefBud** [comment] 2022-10-24 14:08
Looks like the same as https://github.com/tullamods/Bagnon/issues/1442. The dev closed it because he thinks the issue is with TipTac and not his addon.

**Comment by n0nsense** [comment] 2022-10-25 05:54
Seems like Bagnon window is not "active" when u open it.
If u will click "head" of bag window - bug disappearing. But u need to click every time when u re-open bags.

**Comment by Voxxel** [comment] 2022-10-26 07:33
I'm using the 10.0 version of TipTac (updated by frozn here: https://github.com/frozn/TipTac ) and there's no such bug with item tooltip displaying.

**Closed** 2022-10-31 23:08 UTC
