### ISSUE TITLE
Void Storage

### ISSUE THREAD

**Issue by Nexus-V** [tullamods/Bagnon#857] opened 2019-01-13 20:52 UTC
I haven't used my void storage in a while and decided to use it to make more room in my bank vault. When void storage opens, it doesn't show what is in storage, nor does it show empty spaces. Instead, each item square has an explanation point showing. !  When I mouse over an object, it will say what the object is but there is no icon for the object.
I'm not receiving any error messages
![image](https://user-images.githubusercontent.com/42078994/51090551-36bf3f00-174b-11e9-9b70-10d42d4cc9e1.png)

**Comment by semecan** [comment] 2019-01-15 17:54
This is a duplicate of [https://github.com/tullamods/Bagnon/issues/816](url) where a fix was posted.

**Closed** 2019-01-24 19:15 UTC
Labels: :hole:  void storage, bug
