### ISSUE TITLE
Bagon not showing bags at all or bank

### ISSUE THREAD

**Issue by JohnnyType2** [tullamods/Bagnon#1501] opened 2022-11-20 12:03 UTC
I've deleted the .lua files but its just the same. is it just me has anyone a work around?

I'm assuming the creator is aware and working on a fix. thanks

**Comment by dartraiden** [comment] 2022-11-20 12:11
Duplicate of https://github.com/tullamods/Bagnon/issues/1491

**Comment by JohnnyType2** [comment] 2022-11-20 12:14
dupe

**Closed** 2022-11-20 12:14 UTC
