### ISSUE TITLE
Sort feature not handling items properly

### ISSUE THREAD

**Issue by bighigg** [tullamods/Bagnon#1323] opened 2021-09-23 14:42 UTC

**Comment by FranciscoSaraiva** [comment] 2021-09-23 14:56
Also having this issue, seems to be related to the sorting of motes in my case. Motes of Life and Motes of Mana get stuck in a sorting loop.

**Comment by h4rdbr0** [comment] 2021-09-23 15:51
Have the same issue with sorting Motes.

**Comment by GiumaSoft** [comment] 2021-09-23 18:54
Its not only for motes, I got this error with several materials in my bags, i.e. essence of fire, medium leather.

Its seem a sort of bug is in sort function, please make some extended tests before release.

**Comment by theeandrew48** [comment] 2021-09-24 02:53
Yes, there is a problem with motes AND Primals such as Fire, Mana, and Nether. I also had it bugging with Light Feathers. I hate all other bag addons so please advise :P

**Comment by WolfxUdK** [comment] 2021-09-24 05:44
#1315 please use the search function before opening duplicate threads

**Comment by Feronas** [comment] 2021-09-24 10:50
Maybe good idea to roll back to the version without this error until this issue resolved ?

**Comment by daBernd** [comment] 2021-09-24 22:26
Same here - Sorting is not working. I only get messages like "this item does not fit in this bag" (freely translated from german), and the sound like it is sorting all the time, but nothig really happens. Only a "/reload ui" can stop the process.

**Comment by Uzwar** [comment] 2021-09-25 10:51
the same problem, only with arrows. I tried different ones.

**Comment by Mattaruu95** [comment] 2021-09-25 15:34
I was able to fix the issue by downloading a previous version of bagnon and replacing the files. Specifically version 9.1.0  https://www.curseforge.com/wow/addons/bagnon/download/3371569
You can find the file location for your addons by clicking the options button 
![image](https://user-images.githubusercontent.com/91383109/134776981-2f6ca334-3e73-47dc-a88d-86d384d598c0.png)
The file path should be something like E:\World of Warcraft\_classic_\Interface\AddOns
So download 9.1.0 then extract to the addons folder and replace all bagnon files. Sort works great again.

**Comment by Blackwidow-sudo** [comment] 2021-09-25 16:06
Same bug: the sort-function gets stuck in a infinite loop.
I doesnt seem like it has anything todo with specific items.
I get this bug with my main but also with my lowlevel twink.

**Comment by jjoose** [comment] 2021-09-25 16:14
still broken after today's update

**Comment by Dragons07** [comment] 2021-09-26 08:04
Yeah getting same issue when pressing the sort button, just starts buggin out and gotta log out and log back in :-(

**Comment by murraytech** [comment] 2021-09-26 19:20
You can open your bank and sort the bank and then sort your bags if it bugs resort the bank.  Else type /reload most of you will have this feature in your addon sets without having to relog.

**Comment by Mara4867** [comment] 2021-09-26 21:51
I love this add on, but the sorting issue made me uninstall it. Every time I sort, even if not at bank or vendor, it goes into this loop of nonstop shuffling. Have to reload UI to get it to stop, or disable add on and then re-enable it. Please fix!

**Comment by JabiTheMage** [comment] 2021-09-27 00:26
light feather bugs it out.

**Comment by JabiTheMage** [comment] 2021-09-27 00:27
https://www.youtube.com/watch?v=6567ySXAUEY this is what happens

**Comment by Blackwidow-sudo** [comment] 2021-09-27 10:51
> 
> 
> light feather bugs it out.

well its not only `light feather`.

**Comment by i93sme** [comment] 2021-09-27 14:05
Guys, revert the following change and it will just work (tm) - https://github.com/tullamods/Wildpants/commit/1d1f8d54e6123a55307cb611139d27b342d066ad

**Comment by i93sme** [comment] 2021-09-27 14:05
I can confirm that with the latest version, and with this change reverted (by hand using Vim..) no more infinite loop for the exact same bag contents.

**Comment by GiumaSoft** [comment] 2021-09-27 14:07
For all need a quick fix revert to version 9.0.7 do the trick, download from curseforge at https://www.curseforge.com/wow/addons/bagnon/download/3318209, since this repo is not directly installable.

**Comment by i93sme** [comment] 2021-09-27 14:08
I've commented (unfortunately) on another issue that tracked the same behavior but that issue was closed. But, that is the breaking change. I hope to see it reverted or even fixed by the author on the next release.

**Comment by i93sme** [comment] 2021-09-27 14:09
Reverting to 9.0.7 will remove some other things. Reverting only the breaking change will allow you to keep all the other goodies.

**Comment by i93sme** [comment] 2021-09-27 14:18
Please follow https://github.com/tullamods/Bagnon/issues/1315 where the investigation is pretty much more in-depth.
The change I mentioned is the breaking change, people are now diving into what really causes this.

**Comment by Acacia-ashkandi** [comment] 2021-09-29 04:34
I'm having the same sorting issues a lot of other people are having. Obviously this addon needs an update to fix the issues. Please do it asap! It's getting frustrating.

**Closed** 2021-10-05 13:23 UTC
