### ISSUE TITLE
Void Storage nothing but "!" on every slot

### ISSUE THREAD

**Issue by seascape195** [tullamods/Bagnon#841] opened 2018-11-16 01:36 UTC
Error code upon accessing void storage using Bagnon:

Date: 2018-11-15 19:33:03
ID: 1
Error occured in: Global
Count: 1
Message: ...AddOns\Bagnon\external\Wildpants\components\item.lua line 409:
   Usage: IsBattlePayItem(bag, slot)
Debug:
   [C]: IsBattlePayItem()
   ...AddOns\Bagnon\external\Wildpants\components\item.lua:409: IsPaid()
   ...AddOns\Bagnon\external\Wildpants\components\item.lua:252: UpdateBorder()
   ...AddOns\Bagnon\external\Wildpants\components\item.lua:228:
      ...AddOns\Bagnon\external\Wildpants\components\item.lua:222
   [C]: ?
   [C]: Update()
   ...AddOns\Bagnon\external\Wildpants\components\item.lua:124:
      ...AddOns\Bagnon\external\Wildpants\components\item.lua:119
   [C]: Show()
   ...AddOns\Bagnon\external\Wildpants\components\item.lua:30: New()
   ...s\Bagnon\external\Wildpants\components\itemFrame.lua:119: Layout()
   ...e\AddOns\Bagnon_VoidStorage\components\itemFrame.lua:49:
      ...e\AddOns\Bagnon_VoidStorage\components\itemFrame.lua:48
Locals:
(*temporary) = "vault"
(*temporary) = 1

AddOns:
  MoncaiCompare, v7.2.0
  Swatter, v8.0.6162 (SwimmingSeadragon)
  AucAdvanced, v8.0.6122 (SwimmingSeadragon)
  AucFilterBasic, v8.0.6149 (SwimmingSeadragon)
  AucStatHistogram, v8.0.6151 (SwimmingSeadragon)
  AucStatiLevel, v8.0.6155 (SwimmingSeadragon)
  AucStatPurchased, v8.0.6152 (SwimmingSeadragon)
  AucStatSimple, v8.0.6153 (SwimmingSeadragon)
  AucStatStdDev, v8.0.6154 (SwimmingSeadragon)
  AucUtilFixAH, v8.0.6156 (SwimmingSeadragon)
  BagBrother, v
  Bagnon, v8.0.7
  BagnonBoE, v1.0
  BagnonGarbage, v1.0
  BagnonVoidStorage, v8.0.7
  DBMCore, v8.0.15
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  Informant, v8.0.6159 (SwimmingSeadragon)
  Pawn, v2.2.31
  Quartz, v3.4.0
  Recount, vv8.0.1e
  SexyMap, vv8.0.8
  ShadowedUnitFrames, vv4.2.1
  Stubby, v8.0.6161 (SwimmingSeadragon)
  BlizRuntimeLib_enUS v8.0.1.80000 <none>
  (ck=344)

**Comment by Reveax** [comment] 2018-12-04 17:03
Same here.

**Comment by DragonNL** [comment] 2018-12-07 18:55
Same for me.

**Comment by semecan** [comment] 2019-01-15 17:54
This is a duplicate of [https://github.com/tullamods/Bagnon/issues/816](url) where a fix was posted.

**Closed** 2019-01-24 19:15 UTC
Labels: :hole:  void storage, bug

**Comment by seascape195** [comment] 2019-01-26 18:57
Why is this closed?  Its not fixed..
