### ISSUE TITLE
6.0.20 bank glitches

### ISSUE THREAD

**Issue by ssateneth** [tullamods/Bagnon#323] opened 2015-02-23 03:16 UTC
The contents of the banks is unresponsive to moving items within the bank or pulling out / putting things into the bank. The bank rows/columns setting is also ignored, coming from 6.0.19.

**Comment by falconeml** [comment] 2015-02-23 06:44
I've encountered this issue as well.  The items ARE being moved into and out of the bank correctly, but to see the changes, you need to close and re-open the bank window.  Possibly related issue: closing the bag window throws a minor error every time.  I first noticed this after vendoring items, but it also affects other panels that open/close bag window including mail, auction house, and bank.

**Comment by Jaliborc** [comment] 2015-02-24 07:15
Can you post the minor error please? I was unable to reproduce the problem so far.

**Comment by ceylina** [comment] 2015-02-25 18:22
6.0.21 is also having this issue. The bank items are not moving properly. What happens is you remove or move something in your bank bag and it will retain the icon in the original spot until you close and reopen your bank tab. No error is displayed, only a visual bug.

**Comment by awaited** [comment] 2015-02-26 18:50
Using 6.1.0 and had this issue twice, but unable to reproduce the problem as well.

**Comment by ceylina** [comment] 2015-02-27 19:09
I deleted my cache folder and wtf settings for bagnon, bagbrother, and bagnon facade and these issues have disappeared. I think an old setting was not being overwritten properly and/or the cache was wonky.

**Comment by Jaliborc** [comment] 2015-03-03 04:59
@ssateneth @falconeml Does the unresponsiveness problem persists in 6.1.3?

**Comment by ssateneth** [comment] 2015-03-03 07:11
no, seems fixed. it ignored my columns setting from 6.0.16 though which was annoying. it fixed otherwise

**Comment by falconeml** [comment] 2015-03-04 01:14
As of 6.1.3, I'm not having any issues.  I DID remove an old "sister add-on" that could have contributed to the errors: Bagnon AccountSearch, which seems to no longer exist although there is still a broken link to it on the curse project page, under Useful Addons.

**Comment by Jaliborc** [comment] 2015-03-04 08:20
Ok, seems like its fixed! :smile:

**Closed by Jaliborc** 2015-03-04 08:20 UTC
Labels: bug
